### ISSUE TITLE
CheckAndSuggest and getSuggestions are not working

### ISSUE THREAD

**Issue by MaltePetersen** [JacobSamro/ngx-spellchecker#1]
Hello, 
so in my project spellcheck and missspelled works but the getSuggestions and checkAndSuggest are not working. CheckAndSuggest is always returning true with an empty string attached, even  if isMisspelled is returning false. Suggest always returns an empty array.

**Comment by JacobSamro** [comment]
Thank for trying out. Will check this and release a fix soon.

**Comment by radha1258** [comment]
@JacobSamro , Can you please let us know whether the issue is fixed or not? We are also facing the same issue. Please help me with this.

**Comment by JacobSamro** [comment]
Really sorry for the delay. Its hard to find time in my busy schedule.  Please update the version to 1.0.4 and share your feedback.

@MaltePetersen @radha1258
