### ISSUE TITLE
SpellCheck and IsMisspelled methods are not working

### ISSUE THREAD

**Issue by sathvikat** [JacobSamro/ngx-spellchecker#8]
@JacobSamro After updating to latest version, getSuggestions method is working fine but then it broke two other methods "spellCheck" and "isMisspelled" which were working fine before the update. 
SpellCheck method is always returning false for all words and isMisspelled is always returning true. 

Can you please help me here?

**Comment by radha1258** [comment]
Hi @JacobSamro, I am also facing the same issue. Can you please check this?

**Comment by JacobSamro** [comment]
Sure, @sathvikat @radha1258 I am working on it. Will fix it in few hours and let you guys know.

**Comment by JacobSamro** [comment]
Hi there,

This issue was fixed on 1.0.5
